---
- name: Include SQLite Setup
  ansible.builtin.include_tasks: sqlite-setup.yml
  when: database_engine == "sqlite"

- name: Include PostgreSQL Client
  ansible.builtin.include_tasks: postgresql-client.yml
  when: database_engine == "postgres"

- name: Include MySQL Client
  ansible.builtin.include_tasks: mysql-client.yml
  when: database_engine == "mysql"
