---
# This file contains tasks for preparing the system for NetBird deployment.

# Task: Update APT package cache.
# Ensures that the package lists are up-to-date before installing new packages.
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # Cache valid for 1 hour.

# Task: Install essential packages.
# These packages are required for Docker, Docker Compose, and firewall management.
- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - docker.io
      - docker-compose
      - ufw
    state: present

# Task: Add Docker GPG key.
# This key is used to verify the authenticity of Docker packages.
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Task: Add Docker APT repository.
# This repository provides the latest Docker packages for Ubuntu.
- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

# Task: Install Docker Engine components.
# Installs Docker CE, Docker CLI, and containerd.io.
- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

# Task: Add current user to the 'docker' group.
# Allows the specified user (ansible_user) to run Docker commands without sudo.
- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

# Task: Configure UFW firewall rules.
# Opens necessary ports for NetBird services and Caddy.
- name: Configure UFW firewall
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "22" # SSH port.
    - "80" # HTTP port (for Caddy ACME challenges and redirects).
    - "443" # HTTPS port (for Caddy).
    - "3478/udp" # STUN/TURN UDP port.
    - "3478/tcp" # STUN/TURN TCP port.
    - "5349/udp" # STUN/TURN TLS/TCP port.
    - "5349/tcp" # STUN/TURN TLS/TCP port.
    - "10000/udp" # NetBird Signal UDP port.
    - "10000/tcp" # NetBird Signal TCP port.
    - "33080/tcp" # NetBird Relay TCP port.
  notify: Restart ufw # Trigger the 'Restart ufw' handler after firewall rules are applied.