---
- name: Create initial password summary file
  template:
    src: initial-passwords.txt.j2
    dest: "{{ netbird_config_dir }}/PASSWORDS-GENERATED.txt"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    backup: yes
  become: yes

- name: Display password generation summary
  debug:
    msg:
      - "✅ Initial passwords generated and saved"
      - "📁 Password file: {{ netbird_config_dir }}/PASSWORDS-GENERATED.txt"
      - "🔐 Keycloak admin: {{ keycloak_admin_password[:8] }}..."
      - "🗄️ PostgreSQL: {{ postgres_password[:8] }}..."
      - "⚠️ Keep these passwords secure!"
