---
- name: Create NetBird environment configuration from template
  template:
    src: netbird.env.j2
    dest: "{{ netbird_config_dir }}/netbird.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    backup: yes
  become: yes

- name: Copy environment file for Docker Compose
  copy:
    src: "{{ netbird_config_dir }}/netbird.env"
    dest: "{{ netbird_base_dir }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    remote_src: yes
  become: yes

- name: Display environment configuration status
  debug:
    msg:
      - "✅ Environment configuration created"
      - "📁 Config file: {{ netbird_config_dir }}/netbird.env"
      - "📁 Docker Compose env: {{ netbird_base_dir }}/.env"
      - "🌐 Domain: {{ netbird_external_domain }}"
      - "🔗 External IP: {{ netbird_external_ip }}"
