---
- name: NetBird Environment Configuration
  block:
    - name: Generate secure passwords
      include_tasks: generate_passwords.yml
      tags: ['passwords']

    - name: Create environment configuration
      include_tasks: create_environment.yml
      tags: ['environment']

    - name: Create password summary file
      include_tasks: create_password_summary.yml
      tags: ['passwords', 'summary']

    - name: Validate environment configuration
      include_tasks: validate_environment.yml
      tags: ['validate']

  rescue:
    - name: Environment configuration failed
      debug:
        msg: "Environment configuration failed. Check the logs above for details."
      failed_when: true
