---
- name: NetBird Docker Deployment
  block:
    - name: Create Docker Compose configuration
      include_tasks: create_docker_compose.yml
      tags: ['docker-compose']

    - name: Create supporting configuration files
      include_tasks: create_config_files.yml
      tags: ['config-files']

    - name: Deploy NetBird services
      include_tasks: deploy_services.yml
      tags: ['deploy']

    - name: Wait for services to be ready
      include_tasks: wait_for_services.yml
      tags: ['health-check']

    - name: Create management scripts
      include_tasks: create_scripts.yml
      tags: ['scripts']

  rescue:
    - name: Deployment failed
      debug:
        msg: "NetBird deployment failed. Check the logs above for details."
      failed_when: true
