---
- name: Cleanup NetBird Management Servers
  hosts: management
  become: true
  vars:
    netbird_state: absent
  roles:
    - netbird-management
    - netbird-signal
    - netbird-dashboard
    - netbird-coturn

- name: Cleanup NetBird Relay Servers
  hosts: relay
  become: true
  vars:
    netbird_state: absent
  roles:
    - netbird-relay

- name: Cleanup Load Balancer
  hosts: reverse_proxy
  become: true
  vars:
    netbird_state: absent
  roles:
    - reverse-proxy
    - haproxy

- name: Cleanup NetBird Infrastructure (Common)
  hosts: all
  become: true
  vars:
    netbird_state: absent
  roles:
    - common
