---
- name: Reset UFW to defaults
  ufw:
    state: reset
  notify: restart ufw
  become: yes

- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  become: yes

- name: Configure UFW rules for NetBird
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop: "{{ firewall_rules }}"
  notify: restart ufw
  become: yes

- name: Enable UFW
  ufw:
    state: enabled
    logging: 'on'
  become: yes

- name: Check UFW status
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Display UFW status
  debug:
    msg: "{{ ufw_status.stdout_lines }}"
