---
- name: Create NetBird base directory
  file:
    path: "{{ netbird_base_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Create NetBird subdirectories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ netbird_config_dir }}"
    - "{{ netbird_scripts_dir }}"
    - "{{ netbird_data_dir }}"
    - "{{ netbird_logs_dir }}"
  become: yes

- name: Display created directories
  debug:
    msg:
      - "NetBird directories created:"
      - "  Base: {{ netbird_base_dir }}"
      - "  Config: {{ netbird_config_dir }}"
      - "  Scripts: {{ netbird_scripts_dir }}"
      - "  Data: {{ netbird_data_dir }}"
      - "  Logs: {{ netbird_logs_dir }}"
