---
- name: System Preparation for NetBird
  block:
    - name: Check system requirements
      include_tasks: check_requirements.yml
      tags: ['requirements']

    - name: Handle dpkg locks before package operations
      include_tasks: handle_dpkg_locks.yml
      tags: ['dpkg-locks']

    - name: Remove existing Docker installations
      include_tasks: remove_docker.yml
      tags: ['docker-cleanup']

    - name: Install required packages
      include_tasks: install_packages.yml
      tags: ['packages']

    - name: Install Docker
      include_tasks: install_docker.yml
      tags: ['docker']

    - name: Configure firewall
      include_tasks: configure_firewall.yml
      tags: ['firewall']
      when: firewall_enabled | default(true)

    - name: Create directory structure
      include_tasks: create_directories.yml
      tags: ['directories']

    - name: Verify installation
      include_tasks: verify_installation.yml
      tags: ['verify']

  rescue:
    - name: System preparation failed
      debug:
        msg: "System preparation failed. Check the logs above for details."
      failed_when: true
