---
- name: Provision NetBird API resources
  hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: netbird_api
  vars:
    netbird_management_url: "{{ lookup('env', 'NETBIRD_MANAGEMENT_URL') | default('https://' + netbird_domain, true) }}"
    netbird_api_token: "{{ lookup('env', 'NETBIRD_API_TOKEN') }}"
    netbird_user_name: "{{ target_user | default('default-user') }}"

- name: Install and Register NetBird Peers
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  roles:
    - role: netbird_client
  vars:
    netbird_setup_key: "{{ hostvars['localhost']['netbird_setup_key'] }}"
    netbird_management_url: "{{ hostvars['localhost']['netbird_management_url'] }}"
    netbird_docker_enabled: "{{ use_docker | default(false) }}"
