---
# Project defaults 
# All versions and sensitive configurations are managed via Terraform and passed through the inventory.
# Only static defaults should remain here.

netbird_data_dir: "/var/lib/netbird"
netbird_config_dir: "/etc/netbird"
