---
# Ensure required packages and directories exist on the host

- name: Ensure required apt packages are present
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - jq
      - git
      - unzip
    state: present
    update_cache: true

- name: Ensure base directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - "{{ tls_dir }}"
    - "{{ netbird_compose_dir }}"
    - "{{ keycloak_compose_dir }}"
    - "{{ traefik_compose_dir }}"

- name: Install Docker engine using official convenience script
  ansible.builtin.shell: |
    set -euo pipefail
    if ! command -v docker >/dev/null 2>&1; then
      curl -fsSL https://get.docker.com | sh
    fi
  args:
    executable: /bin/bash
  register: docker_install
  changed_when: docker_install.rc == 0 and docker_install.stdout != ""

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true