---
# This file contains tasks for deploying NetBird services with Caddy.

# Task: Create the main deployment directory for NetBird.
# This directory will host all the generated configuration files and Docker Compose setup.
- name: Create NetBird deployment directory
  ansible.builtin.file:
    path: /opt/netbird
    state: directory
    mode: '0755'

# Task: Generate the Caddyfile from its Jinja2 template.
# The Caddyfile configures the Caddy reverse proxy for NetBird services.
- name: Generate Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /opt/netbird/Caddyfile
    mode: '0644'

# Task: Generate the docker-compose.yml file from its Jinja2 template.
# This file defines all the Docker services required for NetBird and Caddy.
- name: Generate docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/netbird/docker-compose.yml
    mode: '0644'

# Task: Generate the management.json file from its Jinja2 template.
# This file contains the core configuration for the NetBird management service.
- name: Generate management.json
  ansible.builtin.template:
    src: management.json.j2
    dest: /opt/netbird/management.json
    mode: '0644'

# Task: Generate the turnserver.conf file from its Jinja2 template.
# This file configures the CoTURN STUN/TURN server.
- name: Generate turnserver.conf
  ansible.builtin.template:
    src: turnserver.conf.j2
    dest: /opt/netbird/turnserver.conf
    mode: '0644'

# Task: Start NetBird services using Docker Compose.
# This task brings up all the defined services, including Caddy, Dashboard, Management, Signal, Relay, and CoTURN.
- name: Start NetBird services with Docker Compose
  community.docker.docker_compose:
    project_src: /opt/netbird
    state: present
  environment:
    # Pass environment variables to the Docker Compose services.
    NETBIRD_DOMAIN: "{{ netbird_domain }}"
    NETBIRD_CADDY_EMAIL: "{{ netbird_caddy_email }}"
    NETBIRD_AUTH_AUDIENCE: "{{ netbird_auth_audience }}"
    NETBIRD_AUTH_CLIENT_ID: "{{ netbird_auth_client_id }}"
    NETBIRD_AUTH_AUTHORITY: "{{ netbird_auth_authority }}"
    NETBIRD_RELAY_SECRET: "{{ netbird_relay_secret }}"
    NETBIRD_TURN_SECRET: "{{ netbird_turn_secret }}"
    NETBIRD_TURN_PASSWORD: "{{ netbird_turn_password }}"
    NETBIRD_DATASTORE_ENCRYPTION_KEY: "{{ netbird_datastore_encryption_key }}"