---
- name: Create NetBird data directory
  ansible.builtin.file:
    path: /var/lib/netbird
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create NetBird directory
  ansible.builtin.file:
    path: /opt/netbird
    state: directory
    mode: '0755'

- name: Create NetBird configuration directory
  ansible.builtin.file:
    path: /etc/netbird
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy Coturn configuration
  ansible.builtin.template:
    src: turnserver.conf.j2
    dest: /etc/netbird/turnserver.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart netbird

- name: Deploy NetBird configuration
  ansible.builtin.template:
    src: management.json.j2
    dest: /etc/netbird/management.json
    owner: root
    group: root
    mode: '0600'
  notify: restart netbird

- name: Deploy docker-compose configuration
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /etc/netbird/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart netbird

- name: Start NetBird services
  community.docker.docker_compose_v2:
    project_src: /etc/netbird
    state: present
    pull: always
