---
- name: Check if NetBird realm exists
  command: >
    docker compose exec keycloak /opt/keycloak/bin/kcadm.sh get realms/{{ keycloak_realm }}
  args:
    chdir: "{{ netbird_base_dir }}"
  become_user: "{{ ansible_user }}"
  become: yes
  register: realm_check
  failed_when: false
  changed_when: false

- name: Create NetBird realm
  command: >
    docker compose exec keycloak /opt/keycloak/bin/kcadm.sh create realms
    --set realm={{ keycloak_realm }}
    --set enabled=true
    --set displayName="NetBird"
    --set registrationAllowed=true
    --set loginWithEmailAllowed=true
    --set duplicateEmailsAllowed=false
    --set resetPasswordAllowed=true
    --set editUsernameAllowed=true
    --set bruteForceProtected=true
  args:
    chdir: "{{ netbird_base_dir }}"
  become_user: "{{ ansible_user }}"
  become: yes
  register: realm_creation
  when: realm_check.rc != 0
  changed_when: realm_creation.rc == 0

- name: Display realm creation status
  debug:
    msg: "✅ NetBird realm created successfully"
  when: realm_check.rc != 0 and realm_creation.rc == 0

- name: Display existing realm status
  debug:
    msg: "✅ NetBird realm already exists"
  when: realm_check.rc == 0
