---
- name: Create password summary file
  template:
    src: password-summary.txt.j2
    dest: "{{ netbird_config_dir }}/IMPORTANT-PASSWORDS.txt"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    backup: yes
  become: yes

- name: Display Keycloak configuration summary
  debug:
    msg:
      - "🎉 NetBird Keycloak setup completed successfully!"
      - ""
      - "✅ NetBird realm created"
      - "✅ NetBird web client configured (netbird-client)"
      - "✅ NetBird device client configured (netbird-device)"
      - "✅ NetBird management client configured (netbird-management)"
      - "✅ Client secrets retrieved from Keycloak and updated in config"
      - "✅ Token validation and audience mapping configured"
      - "✅ Admin role and permissions configured"
      - "✅ Test user created with admin role"
      - ""
      - "🌐 Access Information:"
      - "  - Keycloak Admin: http://{{ netbird_external_domain }}:{{ netbird_keycloak_port }}/admin"
      - "  - NetBird Dashboard: http://{{ netbird_external_domain }}:{{ netbird_dashboard_port }}"
      - "  - NetBird Realm: http://{{ netbird_external_domain }}:{{ netbird_keycloak_port }}/realms/{{ keycloak_realm }}"
      - ""
      - "🔐 Test Credentials:"
      - "  - Username: {{ netbird_test_user }}"
      - "  - Password: {{ netbird_test_password }}"
      - ""
      - "📋 Next Steps:"
      - "1. Access NetBird Dashboard at http://{{ netbird_external_domain }}:{{ netbird_dashboard_port }}"
      - "2. Login with the test user credentials"
      - "3. Create additional users in Keycloak admin console"
      - "4. Install NetBird clients on devices to connect"
      - ""
      - "🚀 Your NetBird control plane is now fully configured!"
      - "🔑 All passwords are stored in: {{ netbird_config_dir }}/IMPORTANT-PASSWORDS.txt"
