---
- name: Wait for Keycloak to be accessible
  uri:
    url: "http://{{ netbird_external_domain }}:{{ netbird_keycloak_port }}/realms/master"
    method: GET
    status_code: [200, 302]
  register: keycloak_ready
  until: keycloak_ready.status in [200, 302]
  retries: 60
  delay: 10

- name: Display Keycloak accessibility
  debug:
    msg: "✅ Keycloak is accessible at http://{{ netbird_external_domain }}:{{ netbird_keycloak_port }}"

- name: Test Keycloak admin endpoint
  uri:
    url: "http://{{ netbird_external_domain }}:{{ netbird_keycloak_port }}/admin"
    method: GET
    status_code: [200, 302, 401]
  register: admin_endpoint
  failed_when: false

- name: Display admin endpoint status
  debug:
    msg: "✅ Keycloak admin endpoint is accessible"
  when: admin_endpoint.status in [200, 302, 401]
