---
- name: Stop Coturn container (Cleanup)
  community.docker.docker_container:
    name: coturn
    state: absent
  when: netbird_state | default('present') == 'absent'

- name: Manage Coturn configuration directory
  ansible.builtin.file:
    path: "/etc/coturn"
    state: "{{ 'directory' if netbird_state | default('present') == 'present' else 'absent' }}"
    owner: root
    group: root
    mode: '0755'

- name: Manage Coturn configuration file
  ansible.builtin.template:
    src: turnserver.conf.j2
    dest: /etc/coturn/turnserver.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Coturn
  when: netbird_state | default('present') == 'present'

- name: Manage Coturn container
  community.docker.docker_container:
    name: coturn
    image: "coturn/coturn:{{ coturn_version }}"
    state: started
    restart_policy: on-failure
    restart_retries: 5
    pull: true
    recreate: false
    network_mode: host
    memory: "1g"
    memory_swap: "1g"
    oom_killer: true
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "3478" ]
      interval: "10s"
      timeout: "5s"
      retries: 3
      start_period: "30s"
    volumes:
      - /etc/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    command: ["-c", "/etc/coturn/turnserver.conf"]
    log_driver: "json-file"
    log_options:
      max-size: "100m"
      max-file: "5"
  when: netbird_state | default('present') == 'present'

- name: Manage Coturn ports (UFW)
  community.general.ufw:
    rule: allow
    delete: "{{ 'no' if netbird_state | default('present') == 'present' else 'yes' }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop:
    - { port: '3478', proto: 'udp', comment: 'Coturn STUN/TURN UDP' }
    - { port: '3478', proto: 'tcp', comment: 'Coturn STUN/TURN TCP' }
    - { port: '{{ coturn_min_port }}:{{ coturn_max_port }}', proto: 'udp', comment: 'Coturn Relay Range' }
