---
all:
  children:
    netbird:
      hosts:
        # Primary NetBird server - LOCAL DEPLOYMENT with real IP
        netbird-primary:
          ansible_host: localhost
          ansible_connection: local
          ansible_user: usherking
          netbird_role: primary
          # Force use of real IP instead of localhost for services
          netbird_external_ip: 192.168.4.123
          netbird_external_domain: 192.168.4.123
          
        # Secondary NetBird server (optional for HA)
        # netbird-secondary:
        #   ansible_host: localhost
        #   ansible_connection: local
        #   ansible_user: usherking
        #   netbird_role: secondary
        #   netbird_external_ip: 192.168.1.230
        #   netbird_external_domain: 192.168.1.230
        
      vars:
        # Network Configuration - LOCAL DEPLOYMENT
        # No SSH needed - runs directly on local machine
        
        # NetBird Configuration - Uses real IP for external access
        netbird_domain: "{{ netbird_external_ip | default(ansible_default_ipv4.address) }}"
        netbird_deployment_dir: "/home/{{ ansible_user }}/netbird-deployment"
        
        # Service Ports
        netbird_dashboard_port: 8081
        netbird_keycloak_port: 8080
        netbird_management_port: 8082
        netbird_signal_port: 10000
        netbird_relay_port: 3479
        netbird_stun_port: 3478
        
        # Docker Configuration
        docker_users:
          - "{{ ansible_user }}"
        
        # Firewall Configuration
        firewall_enabled: true
        firewall_default_policy_incoming: deny
        firewall_default_policy_outgoing: allow
