---
# defaults file for keycloak role

# Mode configuration - exactly one must be true
keycloak_deploy_mode: true
keycloak_external_mode: false

# Keycloak deployment configuration
keycloak_version: "22.0"
keycloak_host: "auth.example.com"  # Your domain that will be configured in reverse proxy
keycloak_http_port: 8080  # Internal HTTP port (will be proxied)
keycloak_admin_user: "admin"
keycloak_admin_password: "ChangeThisSecurePassword!"  # Use Ansible Vault in production
keycloak_db_password: "ChangeThisDatabasePassword!"  # Use Ansible Vault in production

# Realm and client configuration
keycloak_realm: "netbird"
keycloak_client_netbird: "netbird-client"
keycloak_client_netbird_backend: "netbird-backend"
keycloak_valid_redirect_uris:
  - "https://YOUR_DOMAIN/*"
  - "http://localhost:53000"
keycloak_web_origins: "+"

# External Keycloak configuration (for external mode)
keycloak_oidc_configuration_endpoint: ""
keycloak_external_client_id: ""
keycloak_external_client_secret: ""  # Use Ansible Vault in production
keycloak_external_mgmt_client_id: ""
keycloak_external_mgmt_client_secret: ""  # Use Ansible Vault in production

# SSL/TLS configuration
# SSL is handled by the reverse proxy (Caddy), not by Keycloak directly
keycloak_validate_certs: true  # Set to false only for testing with self-signed certs on reverse proxy

# Docker configuration
keycloak_data_dir: "/opt/keycloak"
keycloak_postgres_version: "15-alpine"

# Timeouts and retries
keycloak_health_check_retries: 30
keycloak_health_check_delay: 10
