---
# Handlers for the system-preparation role.
# Handlers are tasks that are run only when notified by other tasks.

# Handler: Restart UFW firewall.
# This ensures that any new firewall rules are applied immediately.
- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted